/**
 * The store directories this build ships with.
 *
 * One JSON file per client list, generated by scripts/import-stores.mjs from
 * the client's own spreadsheet. Adding a second client is adding a file and a
 * line here - nothing else in SiteBoss knows the word Lidl.
 *
 * Resolving happens once per process rather than per request: the file is
 * static, and 1,300 stores parsed on every keystroke would be work done for
 * nothing.
 *
 * Server-side only by convention rather than by a guard: the whole list is
 * about 150 KB, and shipping that to a phone on site so it can filter it
 * locally is the wrong trade when the page is server-rendered anyway.
 */

import lidlGb from "@/lib/stores/lidl-gb.json";
import {
  resolveStore,
  type ResolvedStore,
  type Store,
  type StoreDirectory,
} from "@/lib/stores/directory";

type DirectoryFile = StoreDirectory & { stores: Store[] };

const FILES: DirectoryFile[] = [lidlGb as DirectoryFile];

export type LoadedDirectory = {
  directory: StoreDirectory;
  stores: ResolvedStore[];
};

const cache = new Map<string, LoadedDirectory>();

function load(file: DirectoryFile): LoadedDirectory {
  const cached = cache.get(file.id);
  if (cached) return cached;
  const { stores, ...directory } = file;
  const loaded: LoadedDirectory = {
    directory,
    stores: stores.map((store) => resolveStore(store, directory)),
  };
  cache.set(file.id, loaded);
  return loaded;
}

/** Every directory, in the order they are offered. */
export function directories(): LoadedDirectory[] {
  return FILES.map(load);
}

/** One directory by id, or null where a project names one this build lacks. */
export function directoryById(id: string): LoadedDirectory | null {
  const file = FILES.find((entry) => entry.id === id);
  return file ? load(file) : null;
}

/** The default directory. Today there is exactly one. */
export function defaultDirectory(): LoadedDirectory {
  return load(FILES[0]);
}

/**
 * One store, wherever it lives.
 *
 * Takes the directory id as well as the code because two clients will one day
 * both have a store 1470.
 */
export function storeFor(directoryId: string, code: string): ResolvedStore | null {
  const loaded = directoryById(directoryId);
  if (!loaded) return null;
  const wanted = code.trim().replace(/\D/g, "").replace(/^0+(?=\d)/, "");
  return (
    loaded.stores.find(
      (store) => store.code.replace(/^0+(?=\d)/, "") === wanted,
    ) ?? null
  );
}

/**
 * One store by number, looked up across every directory this build ships.
 *
 * The default directory wins a tie, which today cannot happen. When a second
 * client's list arrives and two of them both have a 1470, the caller passes a
 * directory id instead - which is why nothing stores a bare code on its own.
 */
export function findStoreAnywhere(code: string): ResolvedStore | null {
  for (const { directory } of directories()) {
    const store = storeFor(directory.id, code);
    if (store) return store;
  }
  return null;
}
