-- Linking a project to a place in a client's store directory.
--
-- A store is a building that outlives the work done in it; a project is one
-- package of works at that building. The same store carries a hoarding
-- replacement one year and a roof repair the next, and each of those is its own
-- project with its own reports, issues, photographs and documents. So this does
-- not merge the two - it records which place a project is at.
--
-- Two columns rather than a stores table, deliberately.
--
-- The directory itself is client reference data: about thirteen hundred rows,
-- identical for every company that uses SiteBoss, changing a few times a year
-- when the client issues a new spreadsheet. It ships with the application
-- (lib/stores/*.json, generated by scripts/import-stores.mjs), which means
-- search is instant with no round trip, an update is a reviewable commit rather
-- than a database write, there is no per-tenant copy to drift, and there is no
-- RLS surface on data that is nobody's secret.
--
-- What the database has to hold is the link, and (directory, code) is exactly
-- what a foreign key would carry. If a company ever needs to define locations
-- of its own - a warehouse, an office, a site with no client directory behind
-- it - a `locations` table can be added later alongside these columns without
-- touching a single existing row.
--
-- Additive and reversible. Both columns are nullable with no default and no
-- backfill: every existing project keeps working untouched and unlinked, store
-- selection is an offer rather than a requirement, and issued PDFs are stored
-- files that this cannot reach.
--
-- To roll back:
--   alter table public.projects
--     drop column if exists location_code,
--     drop column if exists location_directory;

alter table public.projects
  add column if not exists location_directory text,
  add column if not exists location_code text;

comment on column public.projects.location_directory is
  'Which client store directory the code belongs to, e.g. lidl-gb. Null for a project entered by hand.';
comment on column public.projects.location_code is
  'The client''s own number for the place, e.g. 1470. Not the project reference: that names the works, this names the building.';

-- Half a link is worse than none: it would name a directory with nothing to
-- look up in it, or a code with no directory to look it up in.
alter table public.projects
  drop constraint if exists projects_location_pair_check;
alter table public.projects
  add constraint projects_location_pair_check check (
    (location_directory is null and location_code is null)
    or (location_directory is not null and location_code is not null)
  );

-- Bounded so a malformed link cannot become an unbounded string. Deliberately
-- not a pattern on the code: a future client may number its sites with letters.
alter table public.projects
  drop constraint if exists projects_location_length_check;
alter table public.projects
  add constraint projects_location_length_check check (
    (location_directory is null or char_length(location_directory) between 1 and 40)
    and (location_code is null or char_length(location_code) between 1 and 32)
  );

-- "Every project at store 1470" - always asked within one company, so the
-- tenant leads. Partial, because most projects have no link and an index entry
-- for each of them would be dead weight.
create index if not exists projects_location_idx
  on public.projects (company_id, location_directory, location_code)
  where location_directory is not null;

-- No policy changes. These are columns on `projects`, which already has
-- company-scoped select, insert, update and delete policies, and `anon` already
-- holds no privilege on the table. Nothing here widens what anybody can read.
